# netlify.toml (Revised Version)

[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.functions/api"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200